-- RioTendas — Diagnóstico central de tráfego e Egress estimado
-- Execute este arquivo uma única vez no SQL Editor do Supabase.

create table if not exists public.riotendas_diagnostico_trafego (
  id bigint generated by default as identity primary key,
  horario timestamptz not null default now(),
  dispositivo_id text not null,
  dispositivo_nome text not null default 'Não identificado',
  usuario_nome text,
  usuario_perfil text,
  versao_sistema text,
  origem text,
  modulo text,
  chamador text,
  operacao text,
  url_resumo text,
  servico text,
  recurso text,
  metodo text,
  status integer,
  sucesso boolean not null default true,
  duracao_ms numeric(12,2) not null default 0,
  bytes_recebidos bigint not null default 0,
  linhas_estimadas integer not null default 0,
  modo_medicao text,
  erro text,
  user_agent text,
  criado_em timestamptz not null default now()
);

create index if not exists idx_rt_diag_horario on public.riotendas_diagnostico_trafego (horario desc);
create index if not exists idx_rt_diag_modulo on public.riotendas_diagnostico_trafego (modulo, horario desc);
create index if not exists idx_rt_diag_recurso on public.riotendas_diagnostico_trafego (recurso, horario desc);
create index if not exists idx_rt_diag_dispositivo on public.riotendas_diagnostico_trafego (dispositivo_id, horario desc);

alter table public.riotendas_diagnostico_trafego enable row level security;

drop policy if exists "rt_diag_insert_anon" on public.riotendas_diagnostico_trafego;
create policy "rt_diag_insert_anon" on public.riotendas_diagnostico_trafego for insert to anon, authenticated with check (true);

drop policy if exists "rt_diag_select_anon" on public.riotendas_diagnostico_trafego;
create policy "rt_diag_select_anon" on public.riotendas_diagnostico_trafego for select to anon, authenticated using (true);

create or replace function public.riotendas_diagnostico_resumo(p_dias integer default 7, p_limite_recentes integer default 200)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with base as (
  select * from public.riotendas_diagnostico_trafego
  where horario >= now() - make_interval(days => greatest(1, least(coalesce(p_dias,7),365)))
),
totais as (
  select count(*)::bigint chamadas,
         coalesce(sum(bytes_recebidos),0)::bigint bytes,
         count(distinct dispositivo_id)::bigint dispositivos,
         coalesce(round(avg(duracao_ms),2),0) media_ms,
         count(*) filter (where not sucesso)::bigint erros
  from base
),
modulo as (
  select coalesce(modulo,'-') nome,count(*)::bigint chamadas,coalesce(sum(bytes_recebidos),0)::bigint bytes,
         coalesce(round(avg(bytes_recebidos),0),0)::bigint media_bytes,coalesce(round(avg(duracao_ms),2),0) media_ms,
         count(*) filter(where not sucesso)::bigint erros from base group by 1 order by bytes desc, chamadas desc limit 50
),
recurso as (
  select coalesce(servico,'-')||' · '||coalesce(recurso,'-') nome,count(*)::bigint chamadas,coalesce(sum(bytes_recebidos),0)::bigint bytes,
         coalesce(round(avg(bytes_recebidos),0),0)::bigint media_bytes,coalesce(round(avg(duracao_ms),2),0) media_ms,
         count(*) filter(where not sucesso)::bigint erros from base group by 1 order by bytes desc, chamadas desc limit 50
),
dispositivo as (
  select coalesce(dispositivo_nome,'-') nome,count(*)::bigint chamadas,coalesce(sum(bytes_recebidos),0)::bigint bytes,
         coalesce(round(avg(bytes_recebidos),0),0)::bigint media_bytes,coalesce(round(avg(duracao_ms),2),0) media_ms,
         count(*) filter(where not sucesso)::bigint erros from base group by 1 order by bytes desc, chamadas desc limit 50
),
versao as (
  select coalesce(versao_sistema,'-') nome,count(*)::bigint chamadas,coalesce(sum(bytes_recebidos),0)::bigint bytes,
         coalesce(round(avg(bytes_recebidos),0),0)::bigint media_bytes,coalesce(round(avg(duracao_ms),2),0) media_ms,
         count(*) filter(where not sucesso)::bigint erros from base group by 1 order by bytes desc, chamadas desc limit 50
),
chamador as (
  select coalesce(chamador,'-') nome,count(*)::bigint chamadas,coalesce(sum(bytes_recebidos),0)::bigint bytes,
         coalesce(round(avg(bytes_recebidos),0),0)::bigint media_bytes,coalesce(round(avg(duracao_ms),2),0) media_ms,
         count(*) filter(where not sucesso)::bigint erros from base group by 1 order by bytes desc, chamadas desc limit 50
),
recentes as (
  select horario,dispositivo_nome,usuario_nome,modulo,servico,recurso,operacao,status,sucesso,bytes_recebidos,duracao_ms,versao_sistema
  from base order by horario desc limit greatest(1,least(coalesce(p_limite_recentes,200),1000))
)
select jsonb_build_object(
  'totais',(select to_jsonb(t) from totais t),
  'por_modulo',coalesce((select jsonb_agg(to_jsonb(x)) from modulo x),'[]'::jsonb),
  'por_recurso',coalesce((select jsonb_agg(to_jsonb(x)) from recurso x),'[]'::jsonb),
  'por_dispositivo',coalesce((select jsonb_agg(to_jsonb(x)) from dispositivo x),'[]'::jsonb),
  'por_versao',coalesce((select jsonb_agg(to_jsonb(x)) from versao x),'[]'::jsonb),
  'por_chamador',coalesce((select jsonb_agg(to_jsonb(x)) from chamador x),'[]'::jsonb),
  'recentes',coalesce((select jsonb_agg(to_jsonb(x)) from recentes x),'[]'::jsonb)
);
$$;

grant execute on function public.riotendas_diagnostico_resumo(integer,integer) to anon, authenticated;

-- Limpeza recomendada: mantenha 90 dias de detalhes.
create or replace function public.riotendas_diagnostico_limpar_antigos(p_dias integer default 90)
returns bigint language plpgsql security definer set search_path=public as $$
declare apagados bigint;
begin
  delete from public.riotendas_diagnostico_trafego where horario < now() - make_interval(days => greatest(30,coalesce(p_dias,90)));
  get diagnostics apagados = row_count;
  return apagados;
end;
$$;
