-- RioTendas - Documentos de eventos centralizados
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.eventos_documentos (
  id bigint generated by default as identity primary key,
  chave text not null unique,
  evento_id text not null,
  cliente_id text,
  cliente_nome text,
  tipo text not null check (tipo in ('guia','contrato','recibo','orcamento')),
  numero text not null,
  nome text not null,
  data_evento date,
  status text not null default 'gerado',
  orcamento_id text,
  html text,
  criado_por text,
  atualizado_por text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists eventos_documentos_evento_idx
  on public.eventos_documentos (evento_id);
create index if not exists eventos_documentos_evento_tipo_idx
  on public.eventos_documentos (evento_id, tipo);
create index if not exists eventos_documentos_atualizado_idx
  on public.eventos_documentos (atualizado_em desc);
create unique index if not exists eventos_documentos_numero_unico_idx
  on public.eventos_documentos (evento_id, tipo, numero);

alter table public.eventos_documentos enable row level security;

-- O RioTendas utiliza autenticação própria no navegador e a chave pública do Supabase.
-- Estas políticas mantêm o mesmo padrão de acesso utilizado pelas demais tabelas do sistema.
drop policy if exists "riotendas_documentos_select" on public.eventos_documentos;
create policy "riotendas_documentos_select"
  on public.eventos_documentos for select
  to anon, authenticated
  using (true);

drop policy if exists "riotendas_documentos_insert" on public.eventos_documentos;
create policy "riotendas_documentos_insert"
  on public.eventos_documentos for insert
  to anon, authenticated
  with check (true);

drop policy if exists "riotendas_documentos_update" on public.eventos_documentos;
create policy "riotendas_documentos_update"
  on public.eventos_documentos for update
  to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "riotendas_documentos_delete" on public.eventos_documentos;
create policy "riotendas_documentos_delete"
  on public.eventos_documentos for delete
  to anon, authenticated
  using (true);

grant select, insert, update, delete on public.eventos_documentos to anon, authenticated;
grant usage, select on sequence public.eventos_documentos_id_seq to anon, authenticated;
